.PHONY:all

all:
	- ./install_cool_plugins.sh
	- ./install_docker.sh
	- ./install_vscode.sh

init-vscode:
	- ./install_vscode.sh

init-docker:
	- ./install_docker.sh

init-cool-plugins:
	- ./install_cool_plugins.sh